### ISSUE TITLE
Major Issue

### ISSUE THREAD

**Issue by pnkr01** [ishitakapoor26/Signify#1]
1. Quiz score state is not maintained as while giving a quiz, if a user presses the back button and then again comes to the quiz, it opens the quiz where the user left it and the score is 0. 

2. Navigator.pop is not widely maintained.

3. Google_nav_bar can be used to improve the bottom navbar.

4. Whenever a user opens the app, whether the user is new or old, they always have to go through the intro_slider.dart file, which is not good.

5. Folder arrangement.

**Comment by ishitakapoor26** [comment]
Hey @pnkr01, thank you for your efforts but I'm already working on it. Also, this is not a repository open for creating issues. You may contribute to Health Bliss project of mine, if you wish to contribute in open-source stuff.
Thank you.
Good Luck!
